"""Generates packages/core/src/dnes/text-fit-table.ts: glyph advance widths of
Spectral BG Medium (the widest weight the Днес horoscope uses) for the characters a
generated reading may contain. The server uses it to check that each part of the daily
horoscope fits two lines on the 360px floor, so the phone never has to cut text.

Run: python scripts/fonts/gen-text-fit-table.py
"""
import io
import sys
from fontTools.ttLib import TTFont

FONT = 'apps/mobile/assets/fonts/SpectralBG-Medium.ttf'
OUT = 'packages/core/src/dnes/text-fit-table.ts'

f = TTFont(FONT)
cmap, hmtx, upm = f.getBestCmap(), f['hmtx'], f['head'].unitsPerEm

chars = [chr(c) for c in range(0x20, 0x7F)]
chars += [chr(c) for c in range(0x0410, 0x0450)] + ['Ё', 'ё']
chars += ['°', '—', '–', '…', '„', '“', '”', '«', '»', '·']

rows = []
for ch in chars:
    g = cmap.get(ord(ch))
    if g is None:
        continue
    rows.append(f"  {ord(ch)}: {hmtx[g][0]},")

body = '\n'.join(rows)
src = f"""// GENERATED by scripts/fonts/gen-text-fit-table.py from SpectralBG-Medium.ttf. Do not edit.
// Advance widths in font units, keyed by code point.
export const TEXT_FIT_UNITS_PER_EM = {upm}

export const TEXT_FIT_ADVANCES: Record<number, number> = {{
{body}
}}
"""
with io.open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
    fh.write(src)
print('wrote', OUT, len(rows), 'glyphs, upm', upm)
