import {
  pgTable,
  text,
  timestamp,
  uuid,
  uniqueIndex,
} from 'drizzle-orm/pg-core'
import { charts } from './charts'
import { crystals } from './crystals'

/**
 * Crystal recommendations
 *
 * Ephemeral recommendations generated by the rules engine based on the
 * user's natal chart, current moon phase, and active transits.
 *
 * Cadence is deliberately sparse — roughly 2-3 recommendations per lunar
 * month (new moon, full moon, and occasional transit triggers). The
 * unique index on (user_id, reason_code, valid_from) ensures we don't
 * double-generate for the same trigger.
 *
 * A recommendation becomes a collected crystal once `collected_at` is set.
 *
 * No RLS — written by generation API routes via service-role client.
 */
export const crystalRecommendations = pgTable(
  'crystal_recommendations',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    userId: text('user_id').notNull(), // Clerk sub
    chartId: uuid('chart_id').references(() => charts.id, {
      onDelete: 'cascade',
    }), // nullable: birthstones can exist without a specific chart selection
    crystalId: uuid('crystal_id')
      .notNull()
      .references(() => crystals.id, { onDelete: 'cascade' }),

    triggerType: text('trigger_type').notNull(), // 'lunar_phase' | 'transit' | 'birthstone'
    reasonCode: text('reason_code').notNull(), // 'full_moon_2026_04', 'saturn_square_moon', 'birthstone_scorpio'
    reasonTextEn: text('reason_text_en').notNull(),
    reasonTextBg: text('reason_text_bg'),

    validFrom: timestamp('valid_from', { withTimezone: true }).notNull(),
    validUntil: timestamp('valid_until', { withTimezone: true }).notNull(),
    collectedAt: timestamp('collected_at', { withTimezone: true }),

    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    uniqueIndex('crystal_recs_user_reason_valid_idx').on(
      table.userId,
      table.reasonCode,
      table.validFrom
    ),
  ]
)

export type CrystalRecommendation = typeof crystalRecommendations.$inferSelect
export type NewCrystalRecommendation =
  typeof crystalRecommendations.$inferInsert
