import { useQuery } from '@tanstack/react-query'

import { useApiClient } from '@/lib/api/client'

/**
 * This month's text for one zodiac sign (Днес v2, swipe page 3).
 *
 * GET /api/sign-month?sign=libra&month=2026-10. One row per sign per month,
 * shared by every user of that sign; generated by the monthly cron, never on
 * demand. A 404 (not generated yet) or any failure resolves to null, and the
 * screen then simply leaves that page out of the swipe. The text changes once a
 * month, so it is cached for the whole session.
 */
export function useMonthlySignText(sign: string | null, month: string) {
  const { apiFetch } = useApiClient()

  return useQuery({
    queryKey: ['sign-month', sign, month],
    enabled: !!sign,
    staleTime: 6 * 60 * 60 * 1000,
    retry: false,
    queryFn: async (): Promise<string | null> => {
      try {
        const raw = (await apiFetch(`/api/sign-month?sign=${encodeURIComponent(sign!)}&month=${month}`)) as {
          content?: unknown
        }
        return typeof raw.content === 'string' && raw.content.trim() ? raw.content.trim() : null
      } catch {
        return null
      }
    },
  })
}
